return {

    Baby = {
        CryNoises = {
            "rbxassetid://78357914113912",
            "rbxassetid://123492535780617",
            "rbxassetid://133712874184243",
            "rbxassetid://124288543356432",
            "rbxassetid://77965804329254",
            "rbxassetid://138983735998908",
            "rbxassetid://121708803426801",
        }
    },
    UnlockItem = "rbxassetid://873617644",
    CloseWindow = "rbxassetid://10128766965",
    OpenWindow = "rbxassetid://15675037413",
    Notification = "rbxassetid://6647898215",
    Lighter = {
        Light = "rbxassetid://18507693047",
        Click = "rbxassetid://9121005783",

    }

}